/*
	Names for the events emiitted through the route class

	The names should be pretty self explanatory 
*/

export const ROUTER_POP_EVENT = 'ROUTER_POP_EVENT'

export const ROUTER_PAGE_NOT_FOUND = 'ROUTER_PAGE_NOT_FOUND'

export const ROUTE_LINK_CLICKED = 'ROUTE_LINK_CLICKED'

export const ROUTE_TRANSITION_LOAD = 'ROUTE_TRANSITION_LOAD'

export const ROUTE_TRANSITION_EXIT = 'ROUTE_TRANSITION_EXIT'

export const ROUTE_TRANSITION_RESOLVED = 'ROUTE_TRANSITION_RESOLVED'

export const ROUTE_TRANSITION_BEFORE_DOM_UPDATE =
	'ROUTE_TRANSITION_BEFORE_DOM_UPDATE'

export const ROUTE_TRANSITION_AFTER_DOM_UPDATE =
	'ROUTE_TRANSITION_AFTER_DOM_UPDATE'

export const ROUTE_TRANSITION_ENTER = 'ROUTE_TRANSITION_ENTER'

export const ROUTE_TRANSITION_COMPLETE = 'ROUTE_TRANSITION_COMPLETE'
